### PR TITLE
./skymax

### PR DESCRIPTION
**Pull request by sralus**
Hello
I have a problem with the output of Skymax. I use an Rasperry Pi 3
Here is the edition of Skymax.
skymax/out# ./skymax
{
"Inverter_mode":4,
"AC_grid_voltage":239.3,
"AC_grid_frequency":49.9,
"AC_out_voltage":230.0,
"AC_out_frequency":50.0,
"PV_in_voltage":198.9,
"PV_in_current":0.0,
"PV_in_watts":0.0,
"PV_in_Welttour":0.0000,
"SCC_voltage":0.0000,
"Load_pct":18,
"Load_watt":877,
"Load_watthour":3.6542,
"Load_va":943,
"Bus_voltage":347,
"Heatsink_temperature":45,
"Battery_capacity":40,
"Battery_voltage":49.70,
"Battery_charge_current":0,
"Battery_discharge_current":4,
"Load_status_on":1,
"SCC_charge_on":1,
"AC_charge_on":0,
"Battery_recharge_voltage":46.0,
"Battery_under_voltage":45.5,
"Battery_bulk_voltage":54.0,
"Battery_float_voltage":53.0,
"Max_grid_charge_current":2,
"Max_charge_current":60,
"Out_source_priority":2,
"Charger_source_priority":1,
"Battery_redischarge_voltage":2436072259697480218988454759890944.0
 
 
Unfortunately, I do not get an issue with:
 
"PV_in_current":0.0,
"PV_in_watts":0.0,
"PV_in_Welttour":0.0000,
"SCC_voltage":0.0000,
 
PV is connected .. see "PV_in_voltage":198.9,”
Maybe one knows what I can change .. get so unfortunately no value for PV Watt displayed in grafana.

I use the  : ISolar SM II 5KW - 450Vdc 5000W 230V Solar Inverter 80A MPPT Parallel Inverter 48V 80A AC Charger.

Thank you in advance.
Sralus

### CODE REVIEW

**Comment by manio** [comment]
Sralus - first of all - I believe you want to create an issue, not a pull request, right?
Maybe someone other can help you with this problem as I currently don't have a PV connected :(
Besides a models/firmware can differ...

**Comment by ned-kelly** [comment]
Hi @sralus - You should make this an issue not a PR...

Next, have you tried running the latest version that's in the[skymax-demo](https://github.com/manio/skymax-demo/) repo - The current project you're trying to do a PR from, is actually behind the latest commits that I pushed up last week.

Cheers,

**Comment by sralus** [comment]
Hi !!
I downloaded the skymax-demo repo.
have created a folder out.
then copeliert with cmake .. && make.
The inverter.conf on device=/dev/hidraw0
then started with ./inverter_poller ... unfortunately then no issue.

THX
Sralus

**Comment by manio** [comment]
As we agreed with @sralus this PR has to be an issue. His problems are now solved. Closing this as invalid.

**Pull request closed without merging**
