### PR TITLE
Suggest merging this with the original project

### PR DESCRIPTION
**Pull request by ned-kelly**
Hi Guys,

I'd like to also merge these additions, as well as my Home Assistant  / docker build (will submit a seperate PR from that project) of this into the original project to make it easier for people wanting to run this on a Pi/ARM chipset (since there's no native watchpower support for ARM CPUs).

### CODE REVIEW

**Comment by manio** [comment]
My initial attemp was only to provide a simple demo :)
You are rather converting it to more usable tool. Thanks!
This way maybe it would be better to rename this project? ;)

Regarding this PR: I can see your commits are a little messed up. You are fixing your own changes (eg in the readme). You are adding binaries. Can you please rebase it and clean it up?
Let me know if you have troubles with this...

**Comment by ned-kelly** [comment]
Hi manio, It's actually not my commits - just another guy @nrm21 who's forked your project, and then I've made additional changes on top of his modifications - Was hoping to get his code into your project before submitting a PR myself...

How about this, once I've cleaned up what I'm [working on](https://github.com/ned-kelly/docker-voltronic-homeassistant), let's merge the codebase, and then have a basic standalone version, and then the docker builds (like I have) for home automation systems, integrations into Grafana etc... I've noticed on your blog post a lot of people are asking about Grafana, so it might be worth including a basic docker compose file for this also...

**Comment by manio** [comment]
Yeah sure - I am open to any good quality PRs :)

**Comment by nrm21** [comment]
@ned-kelly @manio 
 
Hello gentlemen, I got notice of this thread in my email due to the @ mention.

Yes I apologize, the poor PR etiquette was me, I'm not a programmer by trade but more of a "hacker who knows how to code" guy who was never properly trained how to use Git, CI-CD, unit testing, etc... or all those things "proper" developers do.  I just wanted to build a C-like executable for my extremely slow/old Rasp-Pi B+ that was constantly connected to my inverter, to pull numbers for my influx/grafana db located on a separate device on my network.

Unfortunately, I don't have as much time to devote to this project as I use to but feel free to use anything I wrote before, heck isn't that what open source is for?  :)

I'll try to keep my eye on this project in the future and who knows, maybe one day I will have time to devote to it again.

**Comment by ned-kelly** [comment]
> I'll try to keep my eye on this project in the future and who knows, maybe one day I will have time to devote to it again.

Awesome mate! A lot of what I've committed is based off your original work, so kudos for being a pioneer ;)

**Pull request closed without merging**
